//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 10:02:54 AM CDT 
//


package com.mastercard.mcwallet.sdk.xml.allservices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mastercard.mcwallet.sdk.xml.allservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ShippingAddressVerificationResponse_QNAME = new QName("", "ShippingAddressVerificationResponse");
    private final static QName _PairingDataType_QNAME = new QName("", "PairingDataType");
    private final static QName _ExpressCheckoutResponse_QNAME = new QName("", "ExpressCheckoutResponse");
    private final static QName _AuthorizePrecheckoutRequest_QNAME = new QName("", "AuthorizePrecheckoutRequest");
    private final static QName _ExpressCheckoutRequest_QNAME = new QName("", "ExpressCheckoutRequest");
    private final static QName _PrecheckoutDataRequest_QNAME = new QName("", "PrecheckoutDataRequest");
    private final static QName _AuthorizeExpressCheckoutRequest_QNAME = new QName("", "AuthorizeExpressCheckoutRequest");
    private final static QName _ShoppingCartResponse_QNAME = new QName("", "ShoppingCartResponse");
    private final static QName _PrecheckoutDataResponse_QNAME = new QName("", "PrecheckoutDataResponse");
    private final static QName _PrecheckoutCards_QNAME = new QName("", "PrecheckoutCards");
    private final static QName _PrecheckoutRewardProgram_QNAME = new QName("", "PrecheckoutRewardProgram");
    private final static QName _ExtensionPoint_QNAME = new QName("", "ExtensionPoint");
    private final static QName _PrecheckoutRewardPrograms_QNAME = new QName("", "PrecheckoutRewardPrograms");
    private final static QName _ShoppingCartRequest_QNAME = new QName("", "ShoppingCartRequest");
    private final static QName _PrecheckoutShippingAddresses_QNAME = new QName("", "PrecheckoutShippingAddresses");
    private final static QName _PairingDataTypes_QNAME = new QName("", "PairingDataTypes");
    private final static QName _Response_QNAME = new QName("", "Response");
    private final static QName _PrecheckoutCard_QNAME = new QName("", "PrecheckoutCard");
    private final static QName _Errors_QNAME = new QName("", "Errors");
    private final static QName _AuthorizePrecheckoutResponse_QNAME = new QName("", "AuthorizePrecheckoutResponse");
    private final static QName _PrecheckoutShippingAddress_QNAME = new QName("", "PrecheckoutShippingAddress");
    private final static QName _Checkout_QNAME = new QName("", "Checkout");
    private final static QName _MerchantTransactions_QNAME = new QName("", "MerchantTransactions");
    private final static QName _AuthorizeCheckoutRequest_QNAME = new QName("", "AuthorizeCheckoutRequest");
    private final static QName _AuthorizeCheckoutResponse_QNAME = new QName("", "AuthorizeCheckoutResponse");
    private final static QName _ShippingAddressVerificationRequest_QNAME = new QName("", "ShippingAddressVerificationRequest");
    private final static QName _PrecheckoutData_QNAME = new QName("", "PrecheckoutData");
    private final static QName _AuthorizeExpressCheckoutResponse_QNAME = new QName("", "AuthorizeExpressCheckoutResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mastercard.mcwallet.sdk.xml.allservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PairingDataType }
     * 
     */
    public PairingDataType createPairingDataType() {
        return new PairingDataType();
    }

    /**
     * Create an instance of {@link ShippingAddressVerificationResponse }
     * 
     */
    public ShippingAddressVerificationResponse createShippingAddressVerificationResponse() {
        return new ShippingAddressVerificationResponse();
    }

    /**
     * Create an instance of {@link ExpressCheckoutResponse }
     * 
     */
    public ExpressCheckoutResponse createExpressCheckoutResponse() {
        return new ExpressCheckoutResponse();
    }

    /**
     * Create an instance of {@link AuthorizePrecheckoutRequest }
     * 
     */
    public AuthorizePrecheckoutRequest createAuthorizePrecheckoutRequest() {
        return new AuthorizePrecheckoutRequest();
    }

    /**
     * Create an instance of {@link ExpressCheckoutRequest }
     * 
     */
    public ExpressCheckoutRequest createExpressCheckoutRequest() {
        return new ExpressCheckoutRequest();
    }

    /**
     * Create an instance of {@link PrecheckoutDataRequest }
     * 
     */
    public PrecheckoutDataRequest createPrecheckoutDataRequest() {
        return new PrecheckoutDataRequest();
    }

    /**
     * Create an instance of {@link ShoppingCartResponse }
     * 
     */
    public ShoppingCartResponse createShoppingCartResponse() {
        return new ShoppingCartResponse();
    }

    /**
     * Create an instance of {@link AuthorizeExpressCheckoutRequest }
     * 
     */
    public AuthorizeExpressCheckoutRequest createAuthorizeExpressCheckoutRequest() {
        return new AuthorizeExpressCheckoutRequest();
    }

    /**
     * Create an instance of {@link PrecheckoutDataResponse }
     * 
     */
    public PrecheckoutDataResponse createPrecheckoutDataResponse() {
        return new PrecheckoutDataResponse();
    }

    /**
     * Create an instance of {@link PrecheckoutCards }
     * 
     */
    public PrecheckoutCards createPrecheckoutCards() {
        return new PrecheckoutCards();
    }

    /**
     * Create an instance of {@link PrecheckoutRewardProgram }
     * 
     */
    public PrecheckoutRewardProgram createPrecheckoutRewardProgram() {
        return new PrecheckoutRewardProgram();
    }

    /**
     * Create an instance of {@link ExtensionPoint }
     * 
     */
    public ExtensionPoint createExtensionPoint() {
        return new ExtensionPoint();
    }

    /**
     * Create an instance of {@link PrecheckoutRewardPrograms }
     * 
     */
    public PrecheckoutRewardPrograms createPrecheckoutRewardPrograms() {
        return new PrecheckoutRewardPrograms();
    }

    /**
     * Create an instance of {@link ShoppingCartRequest }
     * 
     */
    public ShoppingCartRequest createShoppingCartRequest() {
        return new ShoppingCartRequest();
    }

    /**
     * Create an instance of {@link PrecheckoutShippingAddresses }
     * 
     */
    public PrecheckoutShippingAddresses createPrecheckoutShippingAddresses() {
        return new PrecheckoutShippingAddresses();
    }

    /**
     * Create an instance of {@link PairingDataTypes }
     * 
     */
    public PairingDataTypes createPairingDataTypes() {
        return new PairingDataTypes();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link PrecheckoutCard }
     * 
     */
    public PrecheckoutCard createPrecheckoutCard() {
        return new PrecheckoutCard();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link AuthorizePrecheckoutResponse }
     * 
     */
    public AuthorizePrecheckoutResponse createAuthorizePrecheckoutResponse() {
        return new AuthorizePrecheckoutResponse();
    }

    /**
     * Create an instance of {@link PrecheckoutShippingAddress }
     * 
     */
    public PrecheckoutShippingAddress createPrecheckoutShippingAddress() {
        return new PrecheckoutShippingAddress();
    }

    /**
     * Create an instance of {@link Checkout }
     * 
     */
    public Checkout createCheckout() {
        return new Checkout();
    }

    /**
     * Create an instance of {@link MerchantTransactions }
     * 
     */
    public MerchantTransactions createMerchantTransactions() {
        return new MerchantTransactions();
    }

    /**
     * Create an instance of {@link AuthorizeCheckoutResponse }
     * 
     */
    public AuthorizeCheckoutResponse createAuthorizeCheckoutResponse() {
        return new AuthorizeCheckoutResponse();
    }

    /**
     * Create an instance of {@link AuthorizeCheckoutRequest }
     * 
     */
    public AuthorizeCheckoutRequest createAuthorizeCheckoutRequest() {
        return new AuthorizeCheckoutRequest();
    }

    /**
     * Create an instance of {@link ShippingAddressVerificationRequest }
     * 
     */
    public ShippingAddressVerificationRequest createShippingAddressVerificationRequest() {
        return new ShippingAddressVerificationRequest();
    }

    /**
     * Create an instance of {@link PrecheckoutData }
     * 
     */
    public PrecheckoutData createPrecheckoutData() {
        return new PrecheckoutData();
    }

    /**
     * Create an instance of {@link AuthorizeExpressCheckoutResponse }
     * 
     */
    public AuthorizeExpressCheckoutResponse createAuthorizeExpressCheckoutResponse() {
        return new AuthorizeExpressCheckoutResponse();
    }

    /**
     * Create an instance of {@link AuthenticationOptions }
     * 
     */
    public AuthenticationOptions createAuthenticationOptions() {
        return new AuthenticationOptions();
    }

    /**
     * Create an instance of {@link VerificationResult }
     * 
     */
    public VerificationResult createVerificationResult() {
        return new VerificationResult();
    }

    /**
     * Create an instance of {@link ShippingAddress }
     * 
     */
    public ShippingAddress createShippingAddress() {
        return new ShippingAddress();
    }

    /**
     * Create an instance of {@link VerifiableAddress }
     * 
     */
    public VerifiableAddress createVerifiableAddress() {
        return new VerifiableAddress();
    }

    /**
     * Create an instance of {@link MerchantTransaction }
     * 
     */
    public MerchantTransaction createMerchantTransaction() {
        return new MerchantTransaction();
    }

    /**
     * Create an instance of {@link RewardProgram }
     * 
     */
    public RewardProgram createRewardProgram() {
        return new RewardProgram();
    }

    /**
     * Create an instance of {@link DateOfBirth }
     * 
     */
    public DateOfBirth createDateOfBirth() {
        return new DateOfBirth();
    }

    /**
     * Create an instance of {@link Details }
     * 
     */
    public Details createDetails() {
        return new Details();
    }

    /**
     * Create an instance of {@link ShoppingCart }
     * 
     */
    public ShoppingCart createShoppingCart() {
        return new ShoppingCart();
    }

    /**
     * Create an instance of {@link Detail }
     * 
     */
    public Detail createDetail() {
        return new Detail();
    }

    /**
     * Create an instance of {@link AuthorizedCheckout }
     * 
     */
    public AuthorizedCheckout createAuthorizedCheckout() {
        return new AuthorizedCheckout();
    }

    /**
     * Create an instance of {@link ShoppingCartItem }
     * 
     */
    public ShoppingCartItem createShoppingCartItem() {
        return new ShoppingCartItem();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link VerificationResults }
     * 
     */
    public VerificationResults createVerificationResults() {
        return new VerificationResults();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link VerifiableAddresses }
     * 
     */
    public VerifiableAddresses createVerifiableAddresses() {
        return new VerifiableAddresses();
    }

    /**
     * Create an instance of {@link Card }
     * 
     */
    public Card createCard() {
        return new Card();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShippingAddressVerificationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingAddressVerificationResponse")
    public JAXBElement<ShippingAddressVerificationResponse> createShippingAddressVerificationResponse(ShippingAddressVerificationResponse value) {
        return new JAXBElement<ShippingAddressVerificationResponse>(_ShippingAddressVerificationResponse_QNAME, ShippingAddressVerificationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PairingDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PairingDataType")
    public JAXBElement<PairingDataType> createPairingDataType(PairingDataType value) {
        return new JAXBElement<PairingDataType>(_PairingDataType_QNAME, PairingDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpressCheckoutResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExpressCheckoutResponse")
    public JAXBElement<ExpressCheckoutResponse> createExpressCheckoutResponse(ExpressCheckoutResponse value) {
        return new JAXBElement<ExpressCheckoutResponse>(_ExpressCheckoutResponse_QNAME, ExpressCheckoutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizePrecheckoutRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuthorizePrecheckoutRequest")
    public JAXBElement<AuthorizePrecheckoutRequest> createAuthorizePrecheckoutRequest(AuthorizePrecheckoutRequest value) {
        return new JAXBElement<AuthorizePrecheckoutRequest>(_AuthorizePrecheckoutRequest_QNAME, AuthorizePrecheckoutRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpressCheckoutRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExpressCheckoutRequest")
    public JAXBElement<ExpressCheckoutRequest> createExpressCheckoutRequest(ExpressCheckoutRequest value) {
        return new JAXBElement<ExpressCheckoutRequest>(_ExpressCheckoutRequest_QNAME, ExpressCheckoutRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrecheckoutDataRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrecheckoutDataRequest")
    public JAXBElement<PrecheckoutDataRequest> createPrecheckoutDataRequest(PrecheckoutDataRequest value) {
        return new JAXBElement<PrecheckoutDataRequest>(_PrecheckoutDataRequest_QNAME, PrecheckoutDataRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizeExpressCheckoutRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuthorizeExpressCheckoutRequest")
    public JAXBElement<AuthorizeExpressCheckoutRequest> createAuthorizeExpressCheckoutRequest(AuthorizeExpressCheckoutRequest value) {
        return new JAXBElement<AuthorizeExpressCheckoutRequest>(_AuthorizeExpressCheckoutRequest_QNAME, AuthorizeExpressCheckoutRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShoppingCartResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShoppingCartResponse")
    public JAXBElement<ShoppingCartResponse> createShoppingCartResponse(ShoppingCartResponse value) {
        return new JAXBElement<ShoppingCartResponse>(_ShoppingCartResponse_QNAME, ShoppingCartResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrecheckoutDataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrecheckoutDataResponse")
    public JAXBElement<PrecheckoutDataResponse> createPrecheckoutDataResponse(PrecheckoutDataResponse value) {
        return new JAXBElement<PrecheckoutDataResponse>(_PrecheckoutDataResponse_QNAME, PrecheckoutDataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrecheckoutCards }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrecheckoutCards")
    public JAXBElement<PrecheckoutCards> createPrecheckoutCards(PrecheckoutCards value) {
        return new JAXBElement<PrecheckoutCards>(_PrecheckoutCards_QNAME, PrecheckoutCards.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrecheckoutRewardProgram }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrecheckoutRewardProgram")
    public JAXBElement<PrecheckoutRewardProgram> createPrecheckoutRewardProgram(PrecheckoutRewardProgram value) {
        return new JAXBElement<PrecheckoutRewardProgram>(_PrecheckoutRewardProgram_QNAME, PrecheckoutRewardProgram.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionPoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExtensionPoint")
    public JAXBElement<ExtensionPoint> createExtensionPoint(ExtensionPoint value) {
        return new JAXBElement<ExtensionPoint>(_ExtensionPoint_QNAME, ExtensionPoint.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrecheckoutRewardPrograms }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrecheckoutRewardPrograms")
    public JAXBElement<PrecheckoutRewardPrograms> createPrecheckoutRewardPrograms(PrecheckoutRewardPrograms value) {
        return new JAXBElement<PrecheckoutRewardPrograms>(_PrecheckoutRewardPrograms_QNAME, PrecheckoutRewardPrograms.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShoppingCartRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShoppingCartRequest")
    public JAXBElement<ShoppingCartRequest> createShoppingCartRequest(ShoppingCartRequest value) {
        return new JAXBElement<ShoppingCartRequest>(_ShoppingCartRequest_QNAME, ShoppingCartRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrecheckoutShippingAddresses }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrecheckoutShippingAddresses")
    public JAXBElement<PrecheckoutShippingAddresses> createPrecheckoutShippingAddresses(PrecheckoutShippingAddresses value) {
        return new JAXBElement<PrecheckoutShippingAddresses>(_PrecheckoutShippingAddresses_QNAME, PrecheckoutShippingAddresses.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PairingDataTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PairingDataTypes")
    public JAXBElement<PairingDataTypes> createPairingDataTypes(PairingDataTypes value) {
        return new JAXBElement<PairingDataTypes>(_PairingDataTypes_QNAME, PairingDataTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Response")
    public JAXBElement<Response> createResponse(Response value) {
        return new JAXBElement<Response>(_Response_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrecheckoutCard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrecheckoutCard")
    public JAXBElement<PrecheckoutCard> createPrecheckoutCard(PrecheckoutCard value) {
        return new JAXBElement<PrecheckoutCard>(_PrecheckoutCard_QNAME, PrecheckoutCard.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Errors }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Errors")
    public JAXBElement<Errors> createErrors(Errors value) {
        return new JAXBElement<Errors>(_Errors_QNAME, Errors.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizePrecheckoutResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuthorizePrecheckoutResponse")
    public JAXBElement<AuthorizePrecheckoutResponse> createAuthorizePrecheckoutResponse(AuthorizePrecheckoutResponse value) {
        return new JAXBElement<AuthorizePrecheckoutResponse>(_AuthorizePrecheckoutResponse_QNAME, AuthorizePrecheckoutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrecheckoutShippingAddress }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrecheckoutShippingAddress")
    public JAXBElement<PrecheckoutShippingAddress> createPrecheckoutShippingAddress(PrecheckoutShippingAddress value) {
        return new JAXBElement<PrecheckoutShippingAddress>(_PrecheckoutShippingAddress_QNAME, PrecheckoutShippingAddress.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Checkout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Checkout")
    public JAXBElement<Checkout> createCheckout(Checkout value) {
        return new JAXBElement<Checkout>(_Checkout_QNAME, Checkout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MerchantTransactions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MerchantTransactions")
    public JAXBElement<MerchantTransactions> createMerchantTransactions(MerchantTransactions value) {
        return new JAXBElement<MerchantTransactions>(_MerchantTransactions_QNAME, MerchantTransactions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizeCheckoutRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuthorizeCheckoutRequest")
    public JAXBElement<AuthorizeCheckoutRequest> createAuthorizeCheckoutRequest(AuthorizeCheckoutRequest value) {
        return new JAXBElement<AuthorizeCheckoutRequest>(_AuthorizeCheckoutRequest_QNAME, AuthorizeCheckoutRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizeCheckoutResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuthorizeCheckoutResponse")
    public JAXBElement<AuthorizeCheckoutResponse> createAuthorizeCheckoutResponse(AuthorizeCheckoutResponse value) {
        return new JAXBElement<AuthorizeCheckoutResponse>(_AuthorizeCheckoutResponse_QNAME, AuthorizeCheckoutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShippingAddressVerificationRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingAddressVerificationRequest")
    public JAXBElement<ShippingAddressVerificationRequest> createShippingAddressVerificationRequest(ShippingAddressVerificationRequest value) {
        return new JAXBElement<ShippingAddressVerificationRequest>(_ShippingAddressVerificationRequest_QNAME, ShippingAddressVerificationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrecheckoutData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrecheckoutData")
    public JAXBElement<PrecheckoutData> createPrecheckoutData(PrecheckoutData value) {
        return new JAXBElement<PrecheckoutData>(_PrecheckoutData_QNAME, PrecheckoutData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizeExpressCheckoutResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AuthorizeExpressCheckoutResponse")
    public JAXBElement<AuthorizeExpressCheckoutResponse> createAuthorizeExpressCheckoutResponse(AuthorizeExpressCheckoutResponse value) {
        return new JAXBElement<AuthorizeExpressCheckoutResponse>(_AuthorizeExpressCheckoutResponse_QNAME, AuthorizeExpressCheckoutResponse.class, null, value);
    }

}
