//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 12:20:47 PM CDT 
//


package com.mastercard.mcwallet.sdk.xml.commontypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mastercard.mcwallet.sdk.xml.commontypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ErrorWrapper_QNAME = new QName("", "ErrorWrapper");
    private final static QName _TransactionDetails_QNAME = new QName("", "TransactionDetails");
    private final static QName _CartItem_QNAME = new QName("", "CartItem");
    private final static QName _Locales_QNAME = new QName("", "Locales");
    private final static QName _WalletProviderWrapper_QNAME = new QName("", "WalletProviderWrapper");
    private final static QName _DataType_QNAME = new QName("", "DataType");
    private final static QName _PairingDataType_QNAME = new QName("", "PairingDataType");
    private final static QName _LoyaltyBrand_QNAME = new QName("", "LoyaltyBrand");
    private final static QName _Merchant_QNAME = new QName("", "Merchant");
    private final static QName _LoyaltyCardWrapper_QNAME = new QName("", "LoyaltyCardWrapper");
    private final static QName _CountrySubdivision_QNAME = new QName("", "CountrySubdivision");
    private final static QName _Countries_QNAME = new QName("", "Countries");
    private final static QName _CheckoutWrapper_QNAME = new QName("", "CheckoutWrapper");
    private final static QName _PaymentCards_QNAME = new QName("", "PaymentCards");
    private final static QName _ExtensionPoint_QNAME = new QName("", "ExtensionPoint");
    private final static QName _MobilePhone_QNAME = new QName("", "MobilePhone");
    private final static QName _LocalUrl_QNAME = new QName("", "LocalUrl");
    private final static QName _DeliveryDestination_QNAME = new QName("", "DeliveryDestination");
    private final static QName _DataTypes_QNAME = new QName("", "DataTypes");
    private final static QName _SecureCodeCardSecurityDetails_QNAME = new QName("", "SecureCodeCardSecurityDetails");
    private final static QName _PairingDataTypes_QNAME = new QName("", "PairingDataTypes");
    private final static QName _Profile_QNAME = new QName("", "Profile");
    private final static QName _ConnectionHistory_QNAME = new QName("", "ConnectionHistory");
    private final static QName _ActivityList_QNAME = new QName("", "ActivityList");
    private final static QName _LoyaltyCard_QNAME = new QName("", "LoyaltyCard");
    private final static QName _Country_QNAME = new QName("", "Country");
    private final static QName _Errors_QNAME = new QName("", "Errors");
    private final static QName _LegalNotice_QNAME = new QName("", "LegalNotice");
    private final static QName _MerchantInfoList_QNAME = new QName("", "MerchantInfoList");
    private final static QName _CardBrandSearch_QNAME = new QName("", "CardBrandSearch");
    private final static QName _DateOfBirth_QNAME = new QName("", "DateOfBirth");
    private final static QName _Activity_QNAME = new QName("", "Activity");
    private final static QName _NamePrefixes_QNAME = new QName("", "NamePrefixes");
    private final static QName _PrivacyPolicy_QNAME = new QName("", "PrivacyPolicy");
    private final static QName _Wallet_QNAME = new QName("", "Wallet");
    private final static QName _CheckoutSelection_QNAME = new QName("", "CheckoutSelection");
    private final static QName _ShippingDestinationWrapper_QNAME = new QName("", "ShippingDestinationWrapper");
    private final static QName _MerchantInfo_QNAME = new QName("", "MerchantInfo");
    private final static QName _SecurityChallenges_QNAME = new QName("", "SecurityChallenges");
    private final static QName _Logo_QNAME = new QName("", "Logo");
    private final static QName _ValidateSecurityChallenge_QNAME = new QName("", "ValidateSecurityChallenge");
    private final static QName _CardSecurityRequired_QNAME = new QName("", "CardSecurityRequired");
    private final static QName _ResponseWrapper_QNAME = new QName("", "ResponseWrapper");
    private final static QName _ShippingDestination_QNAME = new QName("", "ShippingDestination");
    private final static QName _Connection_QNAME = new QName("", "Connection");
    private final static QName _ShoppingCart_QNAME = new QName("", "ShoppingCart");
    private final static QName _LoyaltyBrandWrapper_QNAME = new QName("", "LoyaltyBrandWrapper");
    private final static QName _PaymentCard_QNAME = new QName("", "PaymentCard");
    private final static QName _CardBrand_QNAME = new QName("", "CardBrand");
    private final static QName _ProfileName_QNAME = new QName("", "ProfileName");
    private final static QName _Preferences_QNAME = new QName("", "Preferences");
    private final static QName _TermsOfUseUrls_QNAME = new QName("", "TermsOfUseUrls");
    private final static QName _PaymentCardWrapper_QNAME = new QName("", "PaymentCardWrapper");
    private final static QName _ShippingDestinations_QNAME = new QName("", "ShippingDestinations");
    private final static QName _CountryCode_QNAME = new QName("", "CountryCode");
    private final static QName _ValidateSecurityChallengeWrapper_QNAME = new QName("", "ValidateSecurityChallengeWrapper");
    private final static QName _PrivacyUrls_QNAME = new QName("", "PrivacyUrls");
    private final static QName _PersonalGreetingWrapper_QNAME = new QName("", "PersonalGreetingWrapper");
    private final static QName _PairingDataTypeWrapper_QNAME = new QName("", "PairingDataTypeWrapper");
    private final static QName _MerchantWrapper_QNAME = new QName("", "MerchantWrapper");
    private final static QName _NamePrefixWrapper_QNAME = new QName("", "NamePrefixWrapper");
    private final static QName _SecurityChallengeWrapper_QNAME = new QName("", "SecurityChallengeWrapper");
    private final static QName _CookiePolicy_QNAME = new QName("", "CookiePolicy");
    private final static QName _SecurityChallenge_QNAME = new QName("", "SecurityChallenge");
    private final static QName _TermsAndConditions_QNAME = new QName("", "TermsAndConditions");
    private final static QName _PersonalGreeting_QNAME = new QName("", "PersonalGreeting");
    private final static QName _LoyaltyCards_QNAME = new QName("", "LoyaltyCards");
    private final static QName _Response_QNAME = new QName("", "Response");
    private final static QName _CookieNoticeUrls_QNAME = new QName("", "CookieNoticeUrls");
    private final static QName _CountrySubdivisions_QNAME = new QName("", "CountrySubdivisions");
    private final static QName _Locale_QNAME = new QName("", "Locale");
    private final static QName _ProfileWrapper_QNAME = new QName("", "ProfileWrapper");
    private final static QName _ConnectionList_QNAME = new QName("", "ConnectionList");
    private final static QName _Error_QNAME = new QName("", "Error");
    private final static QName _WalletProvider_QNAME = new QName("", "WalletProvider");
    private final static QName _WalletWrapper_QNAME = new QName("", "WalletWrapper");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _Checkout_QNAME = new QName("", "Checkout");
    private final static QName _NamePrefix_QNAME = new QName("", "NamePrefix");
    private final static QName _Address_QNAME = new QName("", "Address");
    private final static QName _ConnectionHistoryList_QNAME = new QName("", "ConnectionHistoryList");
    private final static QName _CardBrands_QNAME = new QName("", "CardBrands");
    private final static QName _InvitationCodeCountries_QNAME = new QName("", "InvitationCodeCountries");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mastercard.mcwallet.sdk.xml.commontypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ErrorWrapper }
     * 
     */
    public ErrorWrapper createErrorWrapper() {
        return new ErrorWrapper();
    }

    /**
     * Create an instance of {@link TransactionDetails }
     * 
     */
    public TransactionDetails createTransactionDetails() {
        return new TransactionDetails();
    }

    /**
     * Create an instance of {@link CartItem }
     * 
     */
    public CartItem createCartItem() {
        return new CartItem();
    }

    /**
     * Create an instance of {@link Locales }
     * 
     */
    public Locales createLocales() {
        return new Locales();
    }

    /**
     * Create an instance of {@link WalletProviderWrapper }
     * 
     */
    public WalletProviderWrapper createWalletProviderWrapper() {
        return new WalletProviderWrapper();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link PairingDataType }
     * 
     */
    public PairingDataType createPairingDataType() {
        return new PairingDataType();
    }

    /**
     * Create an instance of {@link LoyaltyBrand }
     * 
     */
    public LoyaltyBrand createLoyaltyBrand() {
        return new LoyaltyBrand();
    }

    /**
     * Create an instance of {@link Merchant }
     * 
     */
    public Merchant createMerchant() {
        return new Merchant();
    }

    /**
     * Create an instance of {@link LoyaltyCardWrapper }
     * 
     */
    public LoyaltyCardWrapper createLoyaltyCardWrapper() {
        return new LoyaltyCardWrapper();
    }

    /**
     * Create an instance of {@link CountrySubdivision }
     * 
     */
    public CountrySubdivision createCountrySubdivision() {
        return new CountrySubdivision();
    }

    /**
     * Create an instance of {@link Countries }
     * 
     */
    public Countries createCountries() {
        return new Countries();
    }

    /**
     * Create an instance of {@link CheckoutWrapper }
     * 
     */
    public CheckoutWrapper createCheckoutWrapper() {
        return new CheckoutWrapper();
    }

    /**
     * Create an instance of {@link PaymentCards }
     * 
     */
    public PaymentCards createPaymentCards() {
        return new PaymentCards();
    }

    /**
     * Create an instance of {@link ExtensionPoint }
     * 
     */
    public ExtensionPoint createExtensionPoint() {
        return new ExtensionPoint();
    }

    /**
     * Create an instance of {@link MobilePhone }
     * 
     */
    public MobilePhone createMobilePhone() {
        return new MobilePhone();
    }

    /**
     * Create an instance of {@link LocalUrl }
     * 
     */
    public LocalUrl createLocalUrl() {
        return new LocalUrl();
    }

    /**
     * Create an instance of {@link SecureCodeCardSecurityDetails }
     * 
     */
    public SecureCodeCardSecurityDetails createSecureCodeCardSecurityDetails() {
        return new SecureCodeCardSecurityDetails();
    }

    /**
     * Create an instance of {@link DataTypes }
     * 
     */
    public DataTypes createDataTypes() {
        return new DataTypes();
    }

    /**
     * Create an instance of {@link DeliveryDestination }
     * 
     */
    public DeliveryDestination createDeliveryDestination() {
        return new DeliveryDestination();
    }

    /**
     * Create an instance of {@link PairingDataTypes }
     * 
     */
    public PairingDataTypes createPairingDataTypes() {
        return new PairingDataTypes();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link ActivityList }
     * 
     */
    public ActivityList createActivityList() {
        return new ActivityList();
    }

    /**
     * Create an instance of {@link ConnectionHistory }
     * 
     */
    public ConnectionHistory createConnectionHistory() {
        return new ConnectionHistory();
    }

    /**
     * Create an instance of {@link LoyaltyCard }
     * 
     */
    public LoyaltyCard createLoyaltyCard() {
        return new LoyaltyCard();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link LegalNotice }
     * 
     */
    public LegalNotice createLegalNotice() {
        return new LegalNotice();
    }

    /**
     * Create an instance of {@link MerchantInfoList }
     * 
     */
    public MerchantInfoList createMerchantInfoList() {
        return new MerchantInfoList();
    }

    /**
     * Create an instance of {@link CardBrandSearch }
     * 
     */
    public CardBrandSearch createCardBrandSearch() {
        return new CardBrandSearch();
    }

    /**
     * Create an instance of {@link DateOfBirth }
     * 
     */
    public DateOfBirth createDateOfBirth() {
        return new DateOfBirth();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link NamePrefixes }
     * 
     */
    public NamePrefixes createNamePrefixes() {
        return new NamePrefixes();
    }

    /**
     * Create an instance of {@link PrivacyPolicy }
     * 
     */
    public PrivacyPolicy createPrivacyPolicy() {
        return new PrivacyPolicy();
    }

    /**
     * Create an instance of {@link Wallet }
     * 
     */
    public Wallet createWallet() {
        return new Wallet();
    }

    /**
     * Create an instance of {@link CheckoutSelection }
     * 
     */
    public CheckoutSelection createCheckoutSelection() {
        return new CheckoutSelection();
    }

    /**
     * Create an instance of {@link ShippingDestinationWrapper }
     * 
     */
    public ShippingDestinationWrapper createShippingDestinationWrapper() {
        return new ShippingDestinationWrapper();
    }

    /**
     * Create an instance of {@link MerchantInfo }
     * 
     */
    public MerchantInfo createMerchantInfo() {
        return new MerchantInfo();
    }

    /**
     * Create an instance of {@link SecurityChallenges }
     * 
     */
    public SecurityChallenges createSecurityChallenges() {
        return new SecurityChallenges();
    }

    /**
     * Create an instance of {@link Logo }
     * 
     */
    public Logo createLogo() {
        return new Logo();
    }

    /**
     * Create an instance of {@link ValidateSecurityChallenge }
     * 
     */
    public ValidateSecurityChallenge createValidateSecurityChallenge() {
        return new ValidateSecurityChallenge();
    }

    /**
     * Create an instance of {@link CardSecurityRequired }
     * 
     */
    public CardSecurityRequired createCardSecurityRequired() {
        return new CardSecurityRequired();
    }

    /**
     * Create an instance of {@link ResponseWrapper }
     * 
     */
    public ResponseWrapper createResponseWrapper() {
        return new ResponseWrapper();
    }

    /**
     * Create an instance of {@link ShippingDestination }
     * 
     */
    public ShippingDestination createShippingDestination() {
        return new ShippingDestination();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link ShoppingCart }
     * 
     */
    public ShoppingCart createShoppingCart() {
        return new ShoppingCart();
    }

    /**
     * Create an instance of {@link LoyaltyBrandWrapper }
     * 
     */
    public LoyaltyBrandWrapper createLoyaltyBrandWrapper() {
        return new LoyaltyBrandWrapper();
    }

    /**
     * Create an instance of {@link PaymentCard }
     * 
     */
    public PaymentCard createPaymentCard() {
        return new PaymentCard();
    }

    /**
     * Create an instance of {@link ProfileName }
     * 
     */
    public ProfileName createProfileName() {
        return new ProfileName();
    }

    /**
     * Create an instance of {@link CardBrand }
     * 
     */
    public CardBrand createCardBrand() {
        return new CardBrand();
    }

    /**
     * Create an instance of {@link Preferences }
     * 
     */
    public Preferences createPreferences() {
        return new Preferences();
    }

    /**
     * Create an instance of {@link PaymentCardWrapper }
     * 
     */
    public PaymentCardWrapper createPaymentCardWrapper() {
        return new PaymentCardWrapper();
    }

    /**
     * Create an instance of {@link TermsOfUseUrls }
     * 
     */
    public TermsOfUseUrls createTermsOfUseUrls() {
        return new TermsOfUseUrls();
    }

    /**
     * Create an instance of {@link ShippingDestinations }
     * 
     */
    public ShippingDestinations createShippingDestinations() {
        return new ShippingDestinations();
    }

    /**
     * Create an instance of {@link ValidateSecurityChallengeWrapper }
     * 
     */
    public ValidateSecurityChallengeWrapper createValidateSecurityChallengeWrapper() {
        return new ValidateSecurityChallengeWrapper();
    }

    /**
     * Create an instance of {@link CountryCode }
     * 
     */
    public CountryCode createCountryCode() {
        return new CountryCode();
    }

    /**
     * Create an instance of {@link PersonalGreetingWrapper }
     * 
     */
    public PersonalGreetingWrapper createPersonalGreetingWrapper() {
        return new PersonalGreetingWrapper();
    }

    /**
     * Create an instance of {@link PrivacyUrls }
     * 
     */
    public PrivacyUrls createPrivacyUrls() {
        return new PrivacyUrls();
    }

    /**
     * Create an instance of {@link PairingDataTypeWrapper }
     * 
     */
    public PairingDataTypeWrapper createPairingDataTypeWrapper() {
        return new PairingDataTypeWrapper();
    }

    /**
     * Create an instance of {@link SecurityChallengeWrapper }
     * 
     */
    public SecurityChallengeWrapper createSecurityChallengeWrapper() {
        return new SecurityChallengeWrapper();
    }

    /**
     * Create an instance of {@link NamePrefixWrapper }
     * 
     */
    public NamePrefixWrapper createNamePrefixWrapper() {
        return new NamePrefixWrapper();
    }

    /**
     * Create an instance of {@link MerchantWrapper }
     * 
     */
    public MerchantWrapper createMerchantWrapper() {
        return new MerchantWrapper();
    }

    /**
     * Create an instance of {@link SecurityChallenge }
     * 
     */
    public SecurityChallenge createSecurityChallenge() {
        return new SecurityChallenge();
    }

    /**
     * Create an instance of {@link CookiePolicy }
     * 
     */
    public CookiePolicy createCookiePolicy() {
        return new CookiePolicy();
    }

    /**
     * Create an instance of {@link TermsAndConditions }
     * 
     */
    public TermsAndConditions createTermsAndConditions() {
        return new TermsAndConditions();
    }

    /**
     * Create an instance of {@link PersonalGreeting }
     * 
     */
    public PersonalGreeting createPersonalGreeting() {
        return new PersonalGreeting();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link LoyaltyCards }
     * 
     */
    public LoyaltyCards createLoyaltyCards() {
        return new LoyaltyCards();
    }

    /**
     * Create an instance of {@link CookieNoticeUrls }
     * 
     */
    public CookieNoticeUrls createCookieNoticeUrls() {
        return new CookieNoticeUrls();
    }

    /**
     * Create an instance of {@link CountrySubdivisions }
     * 
     */
    public CountrySubdivisions createCountrySubdivisions() {
        return new CountrySubdivisions();
    }

    /**
     * Create an instance of {@link Locale }
     * 
     */
    public Locale createLocale() {
        return new Locale();
    }

    /**
     * Create an instance of {@link ProfileWrapper }
     * 
     */
    public ProfileWrapper createProfileWrapper() {
        return new ProfileWrapper();
    }

    /**
     * Create an instance of {@link ConnectionList }
     * 
     */
    public ConnectionList createConnectionList() {
        return new ConnectionList();
    }

    /**
     * Create an instance of {@link WalletProvider }
     * 
     */
    public WalletProvider createWalletProvider() {
        return new WalletProvider();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link WalletWrapper }
     * 
     */
    public WalletWrapper createWalletWrapper() {
        return new WalletWrapper();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Checkout }
     * 
     */
    public Checkout createCheckout() {
        return new Checkout();
    }

    /**
     * Create an instance of {@link NamePrefix }
     * 
     */
    public NamePrefix createNamePrefix() {
        return new NamePrefix();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ConnectionHistoryList }
     * 
     */
    public ConnectionHistoryList createConnectionHistoryList() {
        return new ConnectionHistoryList();
    }

    /**
     * Create an instance of {@link CardBrands }
     * 
     */
    public CardBrands createCardBrands() {
        return new CardBrands();
    }

    /**
     * Create an instance of {@link InvitationCodeCountries }
     * 
     */
    public InvitationCodeCountries createInvitationCodeCountries() {
        return new InvitationCodeCountries();
    }

    /**
     * Create an instance of {@link Captcha }
     * 
     */
    public Captcha createCaptcha() {
        return new Captcha();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ErrorWrapper")
    public JAXBElement<ErrorWrapper> createErrorWrapper(ErrorWrapper value) {
        return new JAXBElement<ErrorWrapper>(_ErrorWrapper_QNAME, ErrorWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionDetails")
    public JAXBElement<TransactionDetails> createTransactionDetails(TransactionDetails value) {
        return new JAXBElement<TransactionDetails>(_TransactionDetails_QNAME, TransactionDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CartItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CartItem")
    public JAXBElement<CartItem> createCartItem(CartItem value) {
        return new JAXBElement<CartItem>(_CartItem_QNAME, CartItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Locales }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Locales")
    public JAXBElement<Locales> createLocales(Locales value) {
        return new JAXBElement<Locales>(_Locales_QNAME, Locales.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WalletProviderWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WalletProviderWrapper")
    public JAXBElement<WalletProviderWrapper> createWalletProviderWrapper(WalletProviderWrapper value) {
        return new JAXBElement<WalletProviderWrapper>(_WalletProviderWrapper_QNAME, WalletProviderWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataType")
    public JAXBElement<DataType> createDataType(DataType value) {
        return new JAXBElement<DataType>(_DataType_QNAME, DataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PairingDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PairingDataType")
    public JAXBElement<PairingDataType> createPairingDataType(PairingDataType value) {
        return new JAXBElement<PairingDataType>(_PairingDataType_QNAME, PairingDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoyaltyBrand }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LoyaltyBrand")
    public JAXBElement<LoyaltyBrand> createLoyaltyBrand(LoyaltyBrand value) {
        return new JAXBElement<LoyaltyBrand>(_LoyaltyBrand_QNAME, LoyaltyBrand.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Merchant }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Merchant")
    public JAXBElement<Merchant> createMerchant(Merchant value) {
        return new JAXBElement<Merchant>(_Merchant_QNAME, Merchant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoyaltyCardWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LoyaltyCardWrapper")
    public JAXBElement<LoyaltyCardWrapper> createLoyaltyCardWrapper(LoyaltyCardWrapper value) {
        return new JAXBElement<LoyaltyCardWrapper>(_LoyaltyCardWrapper_QNAME, LoyaltyCardWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountrySubdivision }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CountrySubdivision")
    public JAXBElement<CountrySubdivision> createCountrySubdivision(CountrySubdivision value) {
        return new JAXBElement<CountrySubdivision>(_CountrySubdivision_QNAME, CountrySubdivision.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Countries }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Countries")
    public JAXBElement<Countries> createCountries(Countries value) {
        return new JAXBElement<Countries>(_Countries_QNAME, Countries.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckoutWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CheckoutWrapper")
    public JAXBElement<CheckoutWrapper> createCheckoutWrapper(CheckoutWrapper value) {
        return new JAXBElement<CheckoutWrapper>(_CheckoutWrapper_QNAME, CheckoutWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaymentCards }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PaymentCards")
    public JAXBElement<PaymentCards> createPaymentCards(PaymentCards value) {
        return new JAXBElement<PaymentCards>(_PaymentCards_QNAME, PaymentCards.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionPoint }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExtensionPoint")
    public JAXBElement<ExtensionPoint> createExtensionPoint(ExtensionPoint value) {
        return new JAXBElement<ExtensionPoint>(_ExtensionPoint_QNAME, ExtensionPoint.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MobilePhone }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MobilePhone")
    public JAXBElement<MobilePhone> createMobilePhone(MobilePhone value) {
        return new JAXBElement<MobilePhone>(_MobilePhone_QNAME, MobilePhone.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalUrl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LocalUrl")
    public JAXBElement<LocalUrl> createLocalUrl(LocalUrl value) {
        return new JAXBElement<LocalUrl>(_LocalUrl_QNAME, LocalUrl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveryDestination }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DeliveryDestination")
    public JAXBElement<DeliveryDestination> createDeliveryDestination(DeliveryDestination value) {
        return new JAXBElement<DeliveryDestination>(_DeliveryDestination_QNAME, DeliveryDestination.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataTypes")
    public JAXBElement<DataTypes> createDataTypes(DataTypes value) {
        return new JAXBElement<DataTypes>(_DataTypes_QNAME, DataTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecureCodeCardSecurityDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SecureCodeCardSecurityDetails")
    public JAXBElement<SecureCodeCardSecurityDetails> createSecureCodeCardSecurityDetails(SecureCodeCardSecurityDetails value) {
        return new JAXBElement<SecureCodeCardSecurityDetails>(_SecureCodeCardSecurityDetails_QNAME, SecureCodeCardSecurityDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PairingDataTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PairingDataTypes")
    public JAXBElement<PairingDataTypes> createPairingDataTypes(PairingDataTypes value) {
        return new JAXBElement<PairingDataTypes>(_PairingDataTypes_QNAME, PairingDataTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Profile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Profile")
    public JAXBElement<Profile> createProfile(Profile value) {
        return new JAXBElement<Profile>(_Profile_QNAME, Profile.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConnectionHistory")
    public JAXBElement<ConnectionHistory> createConnectionHistory(ConnectionHistory value) {
        return new JAXBElement<ConnectionHistory>(_ConnectionHistory_QNAME, ConnectionHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivityList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ActivityList")
    public JAXBElement<ActivityList> createActivityList(ActivityList value) {
        return new JAXBElement<ActivityList>(_ActivityList_QNAME, ActivityList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoyaltyCard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LoyaltyCard")
    public JAXBElement<LoyaltyCard> createLoyaltyCard(LoyaltyCard value) {
        return new JAXBElement<LoyaltyCard>(_LoyaltyCard_QNAME, LoyaltyCard.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Country }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Country")
    public JAXBElement<Country> createCountry(Country value) {
        return new JAXBElement<Country>(_Country_QNAME, Country.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Errors }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Errors")
    public JAXBElement<Errors> createErrors(Errors value) {
        return new JAXBElement<Errors>(_Errors_QNAME, Errors.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegalNotice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LegalNotice")
    public JAXBElement<LegalNotice> createLegalNotice(LegalNotice value) {
        return new JAXBElement<LegalNotice>(_LegalNotice_QNAME, LegalNotice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MerchantInfoList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MerchantInfoList")
    public JAXBElement<MerchantInfoList> createMerchantInfoList(MerchantInfoList value) {
        return new JAXBElement<MerchantInfoList>(_MerchantInfoList_QNAME, MerchantInfoList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CardBrandSearch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CardBrandSearch")
    public JAXBElement<CardBrandSearch> createCardBrandSearch(CardBrandSearch value) {
        return new JAXBElement<CardBrandSearch>(_CardBrandSearch_QNAME, CardBrandSearch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateOfBirth }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateOfBirth")
    public JAXBElement<DateOfBirth> createDateOfBirth(DateOfBirth value) {
        return new JAXBElement<DateOfBirth>(_DateOfBirth_QNAME, DateOfBirth.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Activity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Activity")
    public JAXBElement<Activity> createActivity(Activity value) {
        return new JAXBElement<Activity>(_Activity_QNAME, Activity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamePrefixes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NamePrefixes")
    public JAXBElement<NamePrefixes> createNamePrefixes(NamePrefixes value) {
        return new JAXBElement<NamePrefixes>(_NamePrefixes_QNAME, NamePrefixes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivacyPolicy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrivacyPolicy")
    public JAXBElement<PrivacyPolicy> createPrivacyPolicy(PrivacyPolicy value) {
        return new JAXBElement<PrivacyPolicy>(_PrivacyPolicy_QNAME, PrivacyPolicy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Wallet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Wallet")
    public JAXBElement<Wallet> createWallet(Wallet value) {
        return new JAXBElement<Wallet>(_Wallet_QNAME, Wallet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckoutSelection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CheckoutSelection")
    public JAXBElement<CheckoutSelection> createCheckoutSelection(CheckoutSelection value) {
        return new JAXBElement<CheckoutSelection>(_CheckoutSelection_QNAME, CheckoutSelection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShippingDestinationWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingDestinationWrapper")
    public JAXBElement<ShippingDestinationWrapper> createShippingDestinationWrapper(ShippingDestinationWrapper value) {
        return new JAXBElement<ShippingDestinationWrapper>(_ShippingDestinationWrapper_QNAME, ShippingDestinationWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MerchantInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MerchantInfo")
    public JAXBElement<MerchantInfo> createMerchantInfo(MerchantInfo value) {
        return new JAXBElement<MerchantInfo>(_MerchantInfo_QNAME, MerchantInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityChallenges }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SecurityChallenges")
    public JAXBElement<SecurityChallenges> createSecurityChallenges(SecurityChallenges value) {
        return new JAXBElement<SecurityChallenges>(_SecurityChallenges_QNAME, SecurityChallenges.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Logo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Logo")
    public JAXBElement<Logo> createLogo(Logo value) {
        return new JAXBElement<Logo>(_Logo_QNAME, Logo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateSecurityChallenge }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ValidateSecurityChallenge")
    public JAXBElement<ValidateSecurityChallenge> createValidateSecurityChallenge(ValidateSecurityChallenge value) {
        return new JAXBElement<ValidateSecurityChallenge>(_ValidateSecurityChallenge_QNAME, ValidateSecurityChallenge.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CardSecurityRequired }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CardSecurityRequired")
    public JAXBElement<CardSecurityRequired> createCardSecurityRequired(CardSecurityRequired value) {
        return new JAXBElement<CardSecurityRequired>(_CardSecurityRequired_QNAME, CardSecurityRequired.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResponseWrapper")
    public JAXBElement<ResponseWrapper> createResponseWrapper(ResponseWrapper value) {
        return new JAXBElement<ResponseWrapper>(_ResponseWrapper_QNAME, ResponseWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShippingDestination }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingDestination")
    public JAXBElement<ShippingDestination> createShippingDestination(ShippingDestination value) {
        return new JAXBElement<ShippingDestination>(_ShippingDestination_QNAME, ShippingDestination.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Connection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Connection")
    public JAXBElement<Connection> createConnection(Connection value) {
        return new JAXBElement<Connection>(_Connection_QNAME, Connection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShoppingCart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShoppingCart")
    public JAXBElement<ShoppingCart> createShoppingCart(ShoppingCart value) {
        return new JAXBElement<ShoppingCart>(_ShoppingCart_QNAME, ShoppingCart.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoyaltyBrandWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LoyaltyBrandWrapper")
    public JAXBElement<LoyaltyBrandWrapper> createLoyaltyBrandWrapper(LoyaltyBrandWrapper value) {
        return new JAXBElement<LoyaltyBrandWrapper>(_LoyaltyBrandWrapper_QNAME, LoyaltyBrandWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaymentCard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PaymentCard")
    public JAXBElement<PaymentCard> createPaymentCard(PaymentCard value) {
        return new JAXBElement<PaymentCard>(_PaymentCard_QNAME, PaymentCard.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CardBrand }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CardBrand")
    public JAXBElement<CardBrand> createCardBrand(CardBrand value) {
        return new JAXBElement<CardBrand>(_CardBrand_QNAME, CardBrand.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProfileName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProfileName")
    public JAXBElement<ProfileName> createProfileName(ProfileName value) {
        return new JAXBElement<ProfileName>(_ProfileName_QNAME, ProfileName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Preferences }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Preferences")
    public JAXBElement<Preferences> createPreferences(Preferences value) {
        return new JAXBElement<Preferences>(_Preferences_QNAME, Preferences.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TermsOfUseUrls }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TermsOfUseUrls")
    public JAXBElement<TermsOfUseUrls> createTermsOfUseUrls(TermsOfUseUrls value) {
        return new JAXBElement<TermsOfUseUrls>(_TermsOfUseUrls_QNAME, TermsOfUseUrls.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaymentCardWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PaymentCardWrapper")
    public JAXBElement<PaymentCardWrapper> createPaymentCardWrapper(PaymentCardWrapper value) {
        return new JAXBElement<PaymentCardWrapper>(_PaymentCardWrapper_QNAME, PaymentCardWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShippingDestinations }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShippingDestinations")
    public JAXBElement<ShippingDestinations> createShippingDestinations(ShippingDestinations value) {
        return new JAXBElement<ShippingDestinations>(_ShippingDestinations_QNAME, ShippingDestinations.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountryCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CountryCode")
    public JAXBElement<CountryCode> createCountryCode(CountryCode value) {
        return new JAXBElement<CountryCode>(_CountryCode_QNAME, CountryCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateSecurityChallengeWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ValidateSecurityChallengeWrapper")
    public JAXBElement<ValidateSecurityChallengeWrapper> createValidateSecurityChallengeWrapper(ValidateSecurityChallengeWrapper value) {
        return new JAXBElement<ValidateSecurityChallengeWrapper>(_ValidateSecurityChallengeWrapper_QNAME, ValidateSecurityChallengeWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivacyUrls }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrivacyUrls")
    public JAXBElement<PrivacyUrls> createPrivacyUrls(PrivacyUrls value) {
        return new JAXBElement<PrivacyUrls>(_PrivacyUrls_QNAME, PrivacyUrls.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonalGreetingWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PersonalGreetingWrapper")
    public JAXBElement<PersonalGreetingWrapper> createPersonalGreetingWrapper(PersonalGreetingWrapper value) {
        return new JAXBElement<PersonalGreetingWrapper>(_PersonalGreetingWrapper_QNAME, PersonalGreetingWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PairingDataTypeWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PairingDataTypeWrapper")
    public JAXBElement<PairingDataTypeWrapper> createPairingDataTypeWrapper(PairingDataTypeWrapper value) {
        return new JAXBElement<PairingDataTypeWrapper>(_PairingDataTypeWrapper_QNAME, PairingDataTypeWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MerchantWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MerchantWrapper")
    public JAXBElement<MerchantWrapper> createMerchantWrapper(MerchantWrapper value) {
        return new JAXBElement<MerchantWrapper>(_MerchantWrapper_QNAME, MerchantWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamePrefixWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NamePrefixWrapper")
    public JAXBElement<NamePrefixWrapper> createNamePrefixWrapper(NamePrefixWrapper value) {
        return new JAXBElement<NamePrefixWrapper>(_NamePrefixWrapper_QNAME, NamePrefixWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityChallengeWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SecurityChallengeWrapper")
    public JAXBElement<SecurityChallengeWrapper> createSecurityChallengeWrapper(SecurityChallengeWrapper value) {
        return new JAXBElement<SecurityChallengeWrapper>(_SecurityChallengeWrapper_QNAME, SecurityChallengeWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CookiePolicy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CookiePolicy")
    public JAXBElement<CookiePolicy> createCookiePolicy(CookiePolicy value) {
        return new JAXBElement<CookiePolicy>(_CookiePolicy_QNAME, CookiePolicy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityChallenge }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SecurityChallenge")
    public JAXBElement<SecurityChallenge> createSecurityChallenge(SecurityChallenge value) {
        return new JAXBElement<SecurityChallenge>(_SecurityChallenge_QNAME, SecurityChallenge.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TermsAndConditions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TermsAndConditions")
    public JAXBElement<TermsAndConditions> createTermsAndConditions(TermsAndConditions value) {
        return new JAXBElement<TermsAndConditions>(_TermsAndConditions_QNAME, TermsAndConditions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonalGreeting }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PersonalGreeting")
    public JAXBElement<PersonalGreeting> createPersonalGreeting(PersonalGreeting value) {
        return new JAXBElement<PersonalGreeting>(_PersonalGreeting_QNAME, PersonalGreeting.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoyaltyCards }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LoyaltyCards")
    public JAXBElement<LoyaltyCards> createLoyaltyCards(LoyaltyCards value) {
        return new JAXBElement<LoyaltyCards>(_LoyaltyCards_QNAME, LoyaltyCards.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Response")
    public JAXBElement<Response> createResponse(Response value) {
        return new JAXBElement<Response>(_Response_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CookieNoticeUrls }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CookieNoticeUrls")
    public JAXBElement<CookieNoticeUrls> createCookieNoticeUrls(CookieNoticeUrls value) {
        return new JAXBElement<CookieNoticeUrls>(_CookieNoticeUrls_QNAME, CookieNoticeUrls.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountrySubdivisions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CountrySubdivisions")
    public JAXBElement<CountrySubdivisions> createCountrySubdivisions(CountrySubdivisions value) {
        return new JAXBElement<CountrySubdivisions>(_CountrySubdivisions_QNAME, CountrySubdivisions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Locale }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Locale")
    public JAXBElement<Locale> createLocale(Locale value) {
        return new JAXBElement<Locale>(_Locale_QNAME, Locale.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProfileWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProfileWrapper")
    public JAXBElement<ProfileWrapper> createProfileWrapper(ProfileWrapper value) {
        return new JAXBElement<ProfileWrapper>(_ProfileWrapper_QNAME, ProfileWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConnectionList")
    public JAXBElement<ConnectionList> createConnectionList(ConnectionList value) {
        return new JAXBElement<ConnectionList>(_ConnectionList_QNAME, ConnectionList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Error }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Error")
    public JAXBElement<Error> createError(Error value) {
        return new JAXBElement<Error>(_Error_QNAME, Error.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WalletProvider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WalletProvider")
    public JAXBElement<WalletProvider> createWalletProvider(WalletProvider value) {
        return new JAXBElement<WalletProvider>(_WalletProvider_QNAME, WalletProvider.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WalletWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WalletWrapper")
    public JAXBElement<WalletWrapper> createWalletWrapper(WalletWrapper value) {
        return new JAXBElement<WalletWrapper>(_WalletWrapper_QNAME, WalletWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Name }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<Name> createName(Name value) {
        return new JAXBElement<Name>(_Name_QNAME, Name.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Checkout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Checkout")
    public JAXBElement<Checkout> createCheckout(Checkout value) {
        return new JAXBElement<Checkout>(_Checkout_QNAME, Checkout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamePrefix }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NamePrefix")
    public JAXBElement<NamePrefix> createNamePrefix(NamePrefix value) {
        return new JAXBElement<NamePrefix>(_NamePrefix_QNAME, NamePrefix.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Address")
    public JAXBElement<Address> createAddress(Address value) {
        return new JAXBElement<Address>(_Address_QNAME, Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectionHistoryList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConnectionHistoryList")
    public JAXBElement<ConnectionHistoryList> createConnectionHistoryList(ConnectionHistoryList value) {
        return new JAXBElement<ConnectionHistoryList>(_ConnectionHistoryList_QNAME, ConnectionHistoryList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CardBrands }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CardBrands")
    public JAXBElement<CardBrands> createCardBrands(CardBrands value) {
        return new JAXBElement<CardBrands>(_CardBrands_QNAME, CardBrands.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvitationCodeCountries }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InvitationCodeCountries")
    public JAXBElement<InvitationCodeCountries> createInvitationCodeCountries(InvitationCodeCountries value) {
        return new JAXBElement<InvitationCodeCountries>(_InvitationCodeCountries_QNAME, InvitationCodeCountries.class, null, value);
    }

}
