//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 12:20:47 PM CDT 
//


package com.mastercard.mcwallet.sdk.xml.commontypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidateSecurityChallengeWrapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidateSecurityChallengeWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValidateSecurityChallenge" type="{}ValidateSecurityChallenge"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidateSecurityChallengeWrapper", propOrder = {
    "validateSecurityChallenge"
})
public class ValidateSecurityChallengeWrapper {

    @XmlElement(name = "ValidateSecurityChallenge", required = true)
    protected ValidateSecurityChallenge validateSecurityChallenge;

    /**
     * Gets the value of the validateSecurityChallenge property.
     * 
     * @return
     *     possible object is
     *     {@link ValidateSecurityChallenge }
     *     
     */
    public ValidateSecurityChallenge getValidateSecurityChallenge() {
        return validateSecurityChallenge;
    }

    /**
     * Sets the value of the validateSecurityChallenge property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidateSecurityChallenge }
     *     
     */
    public void setValidateSecurityChallenge(ValidateSecurityChallenge value) {
        this.validateSecurityChallenge = value;
    }

}
